#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SAP_Db")]
	public partial class SAPDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGheybat_Tbl(Gheybat_Tbl instance);
    partial void UpdateGheybat_Tbl(Gheybat_Tbl instance);
    partial void DeleteGheybat_Tbl(Gheybat_Tbl instance);
    partial void InsertMavared_Tbl(Mavared_Tbl instance);
    partial void UpdateMavared_Tbl(Mavared_Tbl instance);
    partial void DeleteMavared_Tbl(Mavared_Tbl instance);
    partial void InsertStudent_Tbl(Student_Tbl instance);
    partial void UpdateStudent_Tbl(Student_Tbl instance);
    partial void DeleteStudent_Tbl(Student_Tbl instance);
    partial void InsertTakhir_Tbl(Takhir_Tbl instance);
    partial void UpdateTakhir_Tbl(Takhir_Tbl instance);
    partial void DeleteTakhir_Tbl(Takhir_Tbl instance);
    partial void InsertTashvigh_Tbl(Tashvigh_Tbl instance);
    partial void UpdateTashvigh_Tbl(Tashvigh_Tbl instance);
    partial void DeleteTashvigh_Tbl(Tashvigh_Tbl instance);
    partial void InsertTazakor_Tbl(Tazakor_Tbl instance);
    partial void UpdateTazakor_Tbl(Tazakor_Tbl instance);
    partial void DeleteTazakor_Tbl(Tazakor_Tbl instance);
    partial void InsertUser_Tbl(User_Tbl instance);
    partial void UpdateUser_Tbl(User_Tbl instance);
    partial void DeleteUser_Tbl(User_Tbl instance);
    #endregion
		
		public SAPDbDataContext() : 
				base(global::DataAccessLayer.Properties.Settings.Default.SAP_DbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SAPDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAPDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAPDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAPDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Gheybat_Tbl> Gheybat_Tbls
		{
			get
			{
				return this.GetTable<Gheybat_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Mavared_Tbl> Mavared_Tbls
		{
			get
			{
				return this.GetTable<Mavared_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Student_Tbl> Student_Tbls
		{
			get
			{
				return this.GetTable<Student_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Takhir_Tbl> Takhir_Tbls
		{
			get
			{
				return this.GetTable<Takhir_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Tashvigh_Tbl> Tashvigh_Tbls
		{
			get
			{
				return this.GetTable<Tashvigh_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Tazakor_Tbl> Tazakor_Tbls
		{
			get
			{
				return this.GetTable<Tazakor_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<User_Tbl> User_Tbls
		{
			get
			{
				return this.GetTable<User_Tbl>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gheybat_Tbl")]
	public partial class Gheybat_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _GheybatDate;
		
		private string _GheybatStudentName;
		
		private string _GheybatStudentCode;
		
		private string _GheybatMoredTypeTitle;
		
		private EntityRef<Mavared_Tbl> _Mavared_Tbl;
		
		private EntityRef<Student_Tbl> _Student_Tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGheybatDateChanging(string value);
    partial void OnGheybatDateChanged();
    partial void OnGheybatStudentNameChanging(string value);
    partial void OnGheybatStudentNameChanged();
    partial void OnGheybatStudentCodeChanging(string value);
    partial void OnGheybatStudentCodeChanged();
    partial void OnGheybatMoredTypeTitleChanging(string value);
    partial void OnGheybatMoredTypeTitleChanged();
    #endregion
		
		public Gheybat_Tbl()
		{
			this._Mavared_Tbl = default(EntityRef<Mavared_Tbl>);
			this._Student_Tbl = default(EntityRef<Student_Tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GheybatDate", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string GheybatDate
		{
			get
			{
				return this._GheybatDate;
			}
			set
			{
				if ((this._GheybatDate != value))
				{
					this.OnGheybatDateChanging(value);
					this.SendPropertyChanging();
					this._GheybatDate = value;
					this.SendPropertyChanged("GheybatDate");
					this.OnGheybatDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GheybatStudentName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string GheybatStudentName
		{
			get
			{
				return this._GheybatStudentName;
			}
			set
			{
				if ((this._GheybatStudentName != value))
				{
					this.OnGheybatStudentNameChanging(value);
					this.SendPropertyChanging();
					this._GheybatStudentName = value;
					this.SendPropertyChanged("GheybatStudentName");
					this.OnGheybatStudentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GheybatStudentCode", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string GheybatStudentCode
		{
			get
			{
				return this._GheybatStudentCode;
			}
			set
			{
				if ((this._GheybatStudentCode != value))
				{
					if (this._Student_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGheybatStudentCodeChanging(value);
					this.SendPropertyChanging();
					this._GheybatStudentCode = value;
					this.SendPropertyChanged("GheybatStudentCode");
					this.OnGheybatStudentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GheybatMoredTypeTitle", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string GheybatMoredTypeTitle
		{
			get
			{
				return this._GheybatMoredTypeTitle;
			}
			set
			{
				if ((this._GheybatMoredTypeTitle != value))
				{
					if (this._Mavared_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGheybatMoredTypeTitleChanging(value);
					this.SendPropertyChanging();
					this._GheybatMoredTypeTitle = value;
					this.SendPropertyChanged("GheybatMoredTypeTitle");
					this.OnGheybatMoredTypeTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mavared_Tbl_Gheybat_Tbl", Storage="_Mavared_Tbl", ThisKey="GheybatMoredTypeTitle", OtherKey="MoredTitle", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Mavared_Tbl Mavared_Tbl
		{
			get
			{
				return this._Mavared_Tbl.Entity;
			}
			set
			{
				Mavared_Tbl previousValue = this._Mavared_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Mavared_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mavared_Tbl.Entity = null;
						previousValue.Gheybat_Tbls.Remove(this);
					}
					this._Mavared_Tbl.Entity = value;
					if ((value != null))
					{
						value.Gheybat_Tbls.Add(this);
						this._GheybatMoredTypeTitle = value.MoredTitle;
					}
					else
					{
						this._GheybatMoredTypeTitle = default(string);
					}
					this.SendPropertyChanged("Mavared_Tbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Gheybat_Tbl", Storage="_Student_Tbl", ThisKey="GheybatStudentCode", OtherKey="StudentCode", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Student_Tbl Student_Tbl
		{
			get
			{
				return this._Student_Tbl.Entity;
			}
			set
			{
				Student_Tbl previousValue = this._Student_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Student_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student_Tbl.Entity = null;
						previousValue.Gheybat_Tbls.Remove(this);
					}
					this._Student_Tbl.Entity = value;
					if ((value != null))
					{
						value.Gheybat_Tbls.Add(this);
						this._GheybatStudentCode = value.StudentCode;
					}
					else
					{
						this._GheybatStudentCode = default(string);
					}
					this.SendPropertyChanged("Student_Tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mavared_Tbl")]
	public partial class Mavared_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MoredTitle;
		
		private string _MoredType;
		
		private short _MoredScore;
		
		private EntitySet<Gheybat_Tbl> _Gheybat_Tbls;
		
		private EntitySet<Takhir_Tbl> _Takhir_Tbls;
		
		private EntitySet<Tazakor_Tbl> _Tazakor_Tbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMoredTitleChanging(string value);
    partial void OnMoredTitleChanged();
    partial void OnMoredTypeChanging(string value);
    partial void OnMoredTypeChanged();
    partial void OnMoredScoreChanging(short value);
    partial void OnMoredScoreChanged();
    #endregion
		
		public Mavared_Tbl()
		{
			this._Gheybat_Tbls = new EntitySet<Gheybat_Tbl>(new Action<Gheybat_Tbl>(this.attach_Gheybat_Tbls), new Action<Gheybat_Tbl>(this.detach_Gheybat_Tbls));
			this._Takhir_Tbls = new EntitySet<Takhir_Tbl>(new Action<Takhir_Tbl>(this.attach_Takhir_Tbls), new Action<Takhir_Tbl>(this.detach_Takhir_Tbls));
			this._Tazakor_Tbls = new EntitySet<Tazakor_Tbl>(new Action<Tazakor_Tbl>(this.attach_Tazakor_Tbls), new Action<Tazakor_Tbl>(this.detach_Tazakor_Tbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoredTitle", DbType="NVarChar(150) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MoredTitle
		{
			get
			{
				return this._MoredTitle;
			}
			set
			{
				if ((this._MoredTitle != value))
				{
					this.OnMoredTitleChanging(value);
					this.SendPropertyChanging();
					this._MoredTitle = value;
					this.SendPropertyChanged("MoredTitle");
					this.OnMoredTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoredType", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MoredType
		{
			get
			{
				return this._MoredType;
			}
			set
			{
				if ((this._MoredType != value))
				{
					this.OnMoredTypeChanging(value);
					this.SendPropertyChanging();
					this._MoredType = value;
					this.SendPropertyChanged("MoredType");
					this.OnMoredTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoredScore", DbType="SmallInt NOT NULL")]
		public short MoredScore
		{
			get
			{
				return this._MoredScore;
			}
			set
			{
				if ((this._MoredScore != value))
				{
					this.OnMoredScoreChanging(value);
					this.SendPropertyChanging();
					this._MoredScore = value;
					this.SendPropertyChanged("MoredScore");
					this.OnMoredScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mavared_Tbl_Gheybat_Tbl", Storage="_Gheybat_Tbls", ThisKey="MoredTitle", OtherKey="GheybatMoredTypeTitle")]
		public EntitySet<Gheybat_Tbl> Gheybat_Tbls
		{
			get
			{
				return this._Gheybat_Tbls;
			}
			set
			{
				this._Gheybat_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mavared_Tbl_Takhir_Tbl", Storage="_Takhir_Tbls", ThisKey="MoredTitle", OtherKey="TakhirMoredTypeTitle")]
		public EntitySet<Takhir_Tbl> Takhir_Tbls
		{
			get
			{
				return this._Takhir_Tbls;
			}
			set
			{
				this._Takhir_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mavared_Tbl_Tazakor_Tbl", Storage="_Tazakor_Tbls", ThisKey="MoredTitle", OtherKey="TazakorMoredTypeTitle")]
		public EntitySet<Tazakor_Tbl> Tazakor_Tbls
		{
			get
			{
				return this._Tazakor_Tbls;
			}
			set
			{
				this._Tazakor_Tbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Gheybat_Tbls(Gheybat_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mavared_Tbl = this;
		}
		
		private void detach_Gheybat_Tbls(Gheybat_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mavared_Tbl = null;
		}
		
		private void attach_Takhir_Tbls(Takhir_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mavared_Tbl = this;
		}
		
		private void detach_Takhir_Tbls(Takhir_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mavared_Tbl = null;
		}
		
		private void attach_Tazakor_Tbls(Tazakor_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mavared_Tbl = this;
		}
		
		private void detach_Tazakor_Tbls(Tazakor_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mavared_Tbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student_Tbl")]
	public partial class Student_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _StudentCode;
		
		private string _StudentFirstName;
		
		private string _StudentLastName;
		
		private string _StudentPayeh;
		
		private string _StudentReshteh;
		
		private string _StudentNationalCode;
		
		private string _StudentProfile;
		
		private string _StudentBimaryKhas;
		
		private string _StudentFatherName;
		
		private string _StudentFatherJob;
		
		private string _StudentFatherMobile;
		
		private string _StudentMotherJob;
		
		private string _StudentMotherMobile;
		
		private bool _StudentLeftParent;
		
		private string _StudentDeadParent;
		
		private string _StudentParentBimary;
		
		private string _StudentHomeAddress;
		
		private string _StudentHomeNumber;
		
		private string _StudentOther;
		
		private short _StudentScore;
		
		private string _StudentRegisterDate;
		
		private EntitySet<Gheybat_Tbl> _Gheybat_Tbls;
		
		private EntitySet<Takhir_Tbl> _Takhir_Tbls;
		
		private EntitySet<Tashvigh_Tbl> _Tashvigh_Tbls;
		
		private EntitySet<Tazakor_Tbl> _Tazakor_Tbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStudentCodeChanging(string value);
    partial void OnStudentCodeChanged();
    partial void OnStudentFirstNameChanging(string value);
    partial void OnStudentFirstNameChanged();
    partial void OnStudentLastNameChanging(string value);
    partial void OnStudentLastNameChanged();
    partial void OnStudentPayehChanging(string value);
    partial void OnStudentPayehChanged();
    partial void OnStudentReshtehChanging(string value);
    partial void OnStudentReshtehChanged();
    partial void OnStudentNationalCodeChanging(string value);
    partial void OnStudentNationalCodeChanged();
    partial void OnStudentProfileChanging(string value);
    partial void OnStudentProfileChanged();
    partial void OnStudentBimaryKhasChanging(string value);
    partial void OnStudentBimaryKhasChanged();
    partial void OnStudentFatherNameChanging(string value);
    partial void OnStudentFatherNameChanged();
    partial void OnStudentFatherJobChanging(string value);
    partial void OnStudentFatherJobChanged();
    partial void OnStudentFatherMobileChanging(string value);
    partial void OnStudentFatherMobileChanged();
    partial void OnStudentMotherJobChanging(string value);
    partial void OnStudentMotherJobChanged();
    partial void OnStudentMotherMobileChanging(string value);
    partial void OnStudentMotherMobileChanged();
    partial void OnStudentLeftParentChanging(bool value);
    partial void OnStudentLeftParentChanged();
    partial void OnStudentDeadParentChanging(string value);
    partial void OnStudentDeadParentChanged();
    partial void OnStudentParentBimaryChanging(string value);
    partial void OnStudentParentBimaryChanged();
    partial void OnStudentHomeAddressChanging(string value);
    partial void OnStudentHomeAddressChanged();
    partial void OnStudentHomeNumberChanging(string value);
    partial void OnStudentHomeNumberChanged();
    partial void OnStudentOtherChanging(string value);
    partial void OnStudentOtherChanged();
    partial void OnStudentScoreChanging(short value);
    partial void OnStudentScoreChanged();
    partial void OnStudentRegisterDateChanging(string value);
    partial void OnStudentRegisterDateChanged();
    #endregion
		
		public Student_Tbl()
		{
			this._Gheybat_Tbls = new EntitySet<Gheybat_Tbl>(new Action<Gheybat_Tbl>(this.attach_Gheybat_Tbls), new Action<Gheybat_Tbl>(this.detach_Gheybat_Tbls));
			this._Takhir_Tbls = new EntitySet<Takhir_Tbl>(new Action<Takhir_Tbl>(this.attach_Takhir_Tbls), new Action<Takhir_Tbl>(this.detach_Takhir_Tbls));
			this._Tashvigh_Tbls = new EntitySet<Tashvigh_Tbl>(new Action<Tashvigh_Tbl>(this.attach_Tashvigh_Tbls), new Action<Tashvigh_Tbl>(this.detach_Tashvigh_Tbls));
			this._Tazakor_Tbls = new EntitySet<Tazakor_Tbl>(new Action<Tazakor_Tbl>(this.attach_Tazakor_Tbls), new Action<Tazakor_Tbl>(this.detach_Tazakor_Tbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL")]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentCode", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StudentCode
		{
			get
			{
				return this._StudentCode;
			}
			set
			{
				if ((this._StudentCode != value))
				{
					this.OnStudentCodeChanging(value);
					this.SendPropertyChanging();
					this._StudentCode = value;
					this.SendPropertyChanged("StudentCode");
					this.OnStudentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentFirstName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string StudentFirstName
		{
			get
			{
				return this._StudentFirstName;
			}
			set
			{
				if ((this._StudentFirstName != value))
				{
					this.OnStudentFirstNameChanging(value);
					this.SendPropertyChanging();
					this._StudentFirstName = value;
					this.SendPropertyChanged("StudentFirstName");
					this.OnStudentFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentLastName", DbType="NVarChar(170) NOT NULL", CanBeNull=false)]
		public string StudentLastName
		{
			get
			{
				return this._StudentLastName;
			}
			set
			{
				if ((this._StudentLastName != value))
				{
					this.OnStudentLastNameChanging(value);
					this.SendPropertyChanging();
					this._StudentLastName = value;
					this.SendPropertyChanged("StudentLastName");
					this.OnStudentLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentPayeh", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string StudentPayeh
		{
			get
			{
				return this._StudentPayeh;
			}
			set
			{
				if ((this._StudentPayeh != value))
				{
					this.OnStudentPayehChanging(value);
					this.SendPropertyChanging();
					this._StudentPayeh = value;
					this.SendPropertyChanged("StudentPayeh");
					this.OnStudentPayehChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentReshteh", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StudentReshteh
		{
			get
			{
				return this._StudentReshteh;
			}
			set
			{
				if ((this._StudentReshteh != value))
				{
					this.OnStudentReshtehChanging(value);
					this.SendPropertyChanging();
					this._StudentReshteh = value;
					this.SendPropertyChanged("StudentReshteh");
					this.OnStudentReshtehChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentNationalCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string StudentNationalCode
		{
			get
			{
				return this._StudentNationalCode;
			}
			set
			{
				if ((this._StudentNationalCode != value))
				{
					this.OnStudentNationalCodeChanging(value);
					this.SendPropertyChanging();
					this._StudentNationalCode = value;
					this.SendPropertyChanged("StudentNationalCode");
					this.OnStudentNationalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentProfile", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StudentProfile
		{
			get
			{
				return this._StudentProfile;
			}
			set
			{
				if ((this._StudentProfile != value))
				{
					this.OnStudentProfileChanging(value);
					this.SendPropertyChanging();
					this._StudentProfile = value;
					this.SendPropertyChanged("StudentProfile");
					this.OnStudentProfileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentBimaryKhas", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StudentBimaryKhas
		{
			get
			{
				return this._StudentBimaryKhas;
			}
			set
			{
				if ((this._StudentBimaryKhas != value))
				{
					this.OnStudentBimaryKhasChanging(value);
					this.SendPropertyChanging();
					this._StudentBimaryKhas = value;
					this.SendPropertyChanged("StudentBimaryKhas");
					this.OnStudentBimaryKhasChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentFatherName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string StudentFatherName
		{
			get
			{
				return this._StudentFatherName;
			}
			set
			{
				if ((this._StudentFatherName != value))
				{
					this.OnStudentFatherNameChanging(value);
					this.SendPropertyChanging();
					this._StudentFatherName = value;
					this.SendPropertyChanged("StudentFatherName");
					this.OnStudentFatherNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentFatherJob", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string StudentFatherJob
		{
			get
			{
				return this._StudentFatherJob;
			}
			set
			{
				if ((this._StudentFatherJob != value))
				{
					this.OnStudentFatherJobChanging(value);
					this.SendPropertyChanging();
					this._StudentFatherJob = value;
					this.SendPropertyChanged("StudentFatherJob");
					this.OnStudentFatherJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentFatherMobile", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string StudentFatherMobile
		{
			get
			{
				return this._StudentFatherMobile;
			}
			set
			{
				if ((this._StudentFatherMobile != value))
				{
					this.OnStudentFatherMobileChanging(value);
					this.SendPropertyChanging();
					this._StudentFatherMobile = value;
					this.SendPropertyChanged("StudentFatherMobile");
					this.OnStudentFatherMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentMotherJob", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string StudentMotherJob
		{
			get
			{
				return this._StudentMotherJob;
			}
			set
			{
				if ((this._StudentMotherJob != value))
				{
					this.OnStudentMotherJobChanging(value);
					this.SendPropertyChanging();
					this._StudentMotherJob = value;
					this.SendPropertyChanged("StudentMotherJob");
					this.OnStudentMotherJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentMotherMobile", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string StudentMotherMobile
		{
			get
			{
				return this._StudentMotherMobile;
			}
			set
			{
				if ((this._StudentMotherMobile != value))
				{
					this.OnStudentMotherMobileChanging(value);
					this.SendPropertyChanging();
					this._StudentMotherMobile = value;
					this.SendPropertyChanged("StudentMotherMobile");
					this.OnStudentMotherMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentLeftParent", DbType="Bit NOT NULL")]
		public bool StudentLeftParent
		{
			get
			{
				return this._StudentLeftParent;
			}
			set
			{
				if ((this._StudentLeftParent != value))
				{
					this.OnStudentLeftParentChanging(value);
					this.SendPropertyChanging();
					this._StudentLeftParent = value;
					this.SendPropertyChanged("StudentLeftParent");
					this.OnStudentLeftParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentDeadParent", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string StudentDeadParent
		{
			get
			{
				return this._StudentDeadParent;
			}
			set
			{
				if ((this._StudentDeadParent != value))
				{
					this.OnStudentDeadParentChanging(value);
					this.SendPropertyChanging();
					this._StudentDeadParent = value;
					this.SendPropertyChanged("StudentDeadParent");
					this.OnStudentDeadParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentParentBimary", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StudentParentBimary
		{
			get
			{
				return this._StudentParentBimary;
			}
			set
			{
				if ((this._StudentParentBimary != value))
				{
					this.OnStudentParentBimaryChanging(value);
					this.SendPropertyChanging();
					this._StudentParentBimary = value;
					this.SendPropertyChanged("StudentParentBimary");
					this.OnStudentParentBimaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentHomeAddress", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StudentHomeAddress
		{
			get
			{
				return this._StudentHomeAddress;
			}
			set
			{
				if ((this._StudentHomeAddress != value))
				{
					this.OnStudentHomeAddressChanging(value);
					this.SendPropertyChanging();
					this._StudentHomeAddress = value;
					this.SendPropertyChanged("StudentHomeAddress");
					this.OnStudentHomeAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentHomeNumber", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string StudentHomeNumber
		{
			get
			{
				return this._StudentHomeNumber;
			}
			set
			{
				if ((this._StudentHomeNumber != value))
				{
					this.OnStudentHomeNumberChanging(value);
					this.SendPropertyChanging();
					this._StudentHomeNumber = value;
					this.SendPropertyChanged("StudentHomeNumber");
					this.OnStudentHomeNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentOther", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StudentOther
		{
			get
			{
				return this._StudentOther;
			}
			set
			{
				if ((this._StudentOther != value))
				{
					this.OnStudentOtherChanging(value);
					this.SendPropertyChanging();
					this._StudentOther = value;
					this.SendPropertyChanged("StudentOther");
					this.OnStudentOtherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentScore", DbType="SmallInt NOT NULL")]
		public short StudentScore
		{
			get
			{
				return this._StudentScore;
			}
			set
			{
				if ((this._StudentScore != value))
				{
					this.OnStudentScoreChanging(value);
					this.SendPropertyChanging();
					this._StudentScore = value;
					this.SendPropertyChanged("StudentScore");
					this.OnStudentScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentRegisterDate", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string StudentRegisterDate
		{
			get
			{
				return this._StudentRegisterDate;
			}
			set
			{
				if ((this._StudentRegisterDate != value))
				{
					this.OnStudentRegisterDateChanging(value);
					this.SendPropertyChanging();
					this._StudentRegisterDate = value;
					this.SendPropertyChanged("StudentRegisterDate");
					this.OnStudentRegisterDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Gheybat_Tbl", Storage="_Gheybat_Tbls", ThisKey="StudentCode", OtherKey="GheybatStudentCode")]
		public EntitySet<Gheybat_Tbl> Gheybat_Tbls
		{
			get
			{
				return this._Gheybat_Tbls;
			}
			set
			{
				this._Gheybat_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Takhir_Tbl", Storage="_Takhir_Tbls", ThisKey="StudentCode", OtherKey="TakhirStudentCode")]
		public EntitySet<Takhir_Tbl> Takhir_Tbls
		{
			get
			{
				return this._Takhir_Tbls;
			}
			set
			{
				this._Takhir_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Tashvigh_Tbl", Storage="_Tashvigh_Tbls", ThisKey="StudentCode", OtherKey="TashvighStudentCode")]
		public EntitySet<Tashvigh_Tbl> Tashvigh_Tbls
		{
			get
			{
				return this._Tashvigh_Tbls;
			}
			set
			{
				this._Tashvigh_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Tazakor_Tbl", Storage="_Tazakor_Tbls", ThisKey="StudentCode", OtherKey="TazakorStudentCode")]
		public EntitySet<Tazakor_Tbl> Tazakor_Tbls
		{
			get
			{
				return this._Tazakor_Tbls;
			}
			set
			{
				this._Tazakor_Tbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Gheybat_Tbls(Gheybat_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = this;
		}
		
		private void detach_Gheybat_Tbls(Gheybat_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = null;
		}
		
		private void attach_Takhir_Tbls(Takhir_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = this;
		}
		
		private void detach_Takhir_Tbls(Takhir_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = null;
		}
		
		private void attach_Tashvigh_Tbls(Tashvigh_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = this;
		}
		
		private void detach_Tashvigh_Tbls(Tashvigh_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = null;
		}
		
		private void attach_Tazakor_Tbls(Tazakor_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = this;
		}
		
		private void detach_Tazakor_Tbls(Tazakor_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Takhir_Tbl")]
	public partial class Takhir_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TakhirDate;
		
		private string _TakhirStudentName;
		
		private string _TakhirStudentCode;
		
		private string _TakhirMoredTypeTitle;
		
		private EntityRef<Mavared_Tbl> _Mavared_Tbl;
		
		private EntityRef<Student_Tbl> _Student_Tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTakhirDateChanging(string value);
    partial void OnTakhirDateChanged();
    partial void OnTakhirStudentNameChanging(string value);
    partial void OnTakhirStudentNameChanged();
    partial void OnTakhirStudentCodeChanging(string value);
    partial void OnTakhirStudentCodeChanged();
    partial void OnTakhirMoredTypeTitleChanging(string value);
    partial void OnTakhirMoredTypeTitleChanged();
    #endregion
		
		public Takhir_Tbl()
		{
			this._Mavared_Tbl = default(EntityRef<Mavared_Tbl>);
			this._Student_Tbl = default(EntityRef<Student_Tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakhirDate", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TakhirDate
		{
			get
			{
				return this._TakhirDate;
			}
			set
			{
				if ((this._TakhirDate != value))
				{
					this.OnTakhirDateChanging(value);
					this.SendPropertyChanging();
					this._TakhirDate = value;
					this.SendPropertyChanged("TakhirDate");
					this.OnTakhirDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakhirStudentName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TakhirStudentName
		{
			get
			{
				return this._TakhirStudentName;
			}
			set
			{
				if ((this._TakhirStudentName != value))
				{
					this.OnTakhirStudentNameChanging(value);
					this.SendPropertyChanging();
					this._TakhirStudentName = value;
					this.SendPropertyChanged("TakhirStudentName");
					this.OnTakhirStudentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakhirStudentCode", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string TakhirStudentCode
		{
			get
			{
				return this._TakhirStudentCode;
			}
			set
			{
				if ((this._TakhirStudentCode != value))
				{
					if (this._Student_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTakhirStudentCodeChanging(value);
					this.SendPropertyChanging();
					this._TakhirStudentCode = value;
					this.SendPropertyChanged("TakhirStudentCode");
					this.OnTakhirStudentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakhirMoredTypeTitle", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string TakhirMoredTypeTitle
		{
			get
			{
				return this._TakhirMoredTypeTitle;
			}
			set
			{
				if ((this._TakhirMoredTypeTitle != value))
				{
					if (this._Mavared_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTakhirMoredTypeTitleChanging(value);
					this.SendPropertyChanging();
					this._TakhirMoredTypeTitle = value;
					this.SendPropertyChanged("TakhirMoredTypeTitle");
					this.OnTakhirMoredTypeTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mavared_Tbl_Takhir_Tbl", Storage="_Mavared_Tbl", ThisKey="TakhirMoredTypeTitle", OtherKey="MoredTitle", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Mavared_Tbl Mavared_Tbl
		{
			get
			{
				return this._Mavared_Tbl.Entity;
			}
			set
			{
				Mavared_Tbl previousValue = this._Mavared_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Mavared_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mavared_Tbl.Entity = null;
						previousValue.Takhir_Tbls.Remove(this);
					}
					this._Mavared_Tbl.Entity = value;
					if ((value != null))
					{
						value.Takhir_Tbls.Add(this);
						this._TakhirMoredTypeTitle = value.MoredTitle;
					}
					else
					{
						this._TakhirMoredTypeTitle = default(string);
					}
					this.SendPropertyChanged("Mavared_Tbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Takhir_Tbl", Storage="_Student_Tbl", ThisKey="TakhirStudentCode", OtherKey="StudentCode", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Student_Tbl Student_Tbl
		{
			get
			{
				return this._Student_Tbl.Entity;
			}
			set
			{
				Student_Tbl previousValue = this._Student_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Student_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student_Tbl.Entity = null;
						previousValue.Takhir_Tbls.Remove(this);
					}
					this._Student_Tbl.Entity = value;
					if ((value != null))
					{
						value.Takhir_Tbls.Add(this);
						this._TakhirStudentCode = value.StudentCode;
					}
					else
					{
						this._TakhirStudentCode = default(string);
					}
					this.SendPropertyChanged("Student_Tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tashvigh_Tbl")]
	public partial class Tashvigh_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TashvighDate;
		
		private string _TashvighElat;
		
		private string _TashvighEghdamKonande;
		
		private string _TashvighMoredTypeTitle;
		
		private string _TashvighStudentCode;
		
		private EntityRef<Student_Tbl> _Student_Tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTashvighDateChanging(string value);
    partial void OnTashvighDateChanged();
    partial void OnTashvighElatChanging(string value);
    partial void OnTashvighElatChanged();
    partial void OnTashvighEghdamKonandeChanging(string value);
    partial void OnTashvighEghdamKonandeChanged();
    partial void OnTashvighMoredTypeTitleChanging(string value);
    partial void OnTashvighMoredTypeTitleChanged();
    partial void OnTashvighStudentCodeChanging(string value);
    partial void OnTashvighStudentCodeChanged();
    #endregion
		
		public Tashvigh_Tbl()
		{
			this._Student_Tbl = default(EntityRef<Student_Tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TashvighDate", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TashvighDate
		{
			get
			{
				return this._TashvighDate;
			}
			set
			{
				if ((this._TashvighDate != value))
				{
					this.OnTashvighDateChanging(value);
					this.SendPropertyChanging();
					this._TashvighDate = value;
					this.SendPropertyChanged("TashvighDate");
					this.OnTashvighDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TashvighElat", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TashvighElat
		{
			get
			{
				return this._TashvighElat;
			}
			set
			{
				if ((this._TashvighElat != value))
				{
					this.OnTashvighElatChanging(value);
					this.SendPropertyChanging();
					this._TashvighElat = value;
					this.SendPropertyChanged("TashvighElat");
					this.OnTashvighElatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TashvighEghdamKonande", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TashvighEghdamKonande
		{
			get
			{
				return this._TashvighEghdamKonande;
			}
			set
			{
				if ((this._TashvighEghdamKonande != value))
				{
					this.OnTashvighEghdamKonandeChanging(value);
					this.SendPropertyChanging();
					this._TashvighEghdamKonande = value;
					this.SendPropertyChanged("TashvighEghdamKonande");
					this.OnTashvighEghdamKonandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TashvighMoredTypeTitle", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string TashvighMoredTypeTitle
		{
			get
			{
				return this._TashvighMoredTypeTitle;
			}
			set
			{
				if ((this._TashvighMoredTypeTitle != value))
				{
					this.OnTashvighMoredTypeTitleChanging(value);
					this.SendPropertyChanging();
					this._TashvighMoredTypeTitle = value;
					this.SendPropertyChanged("TashvighMoredTypeTitle");
					this.OnTashvighMoredTypeTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TashvighStudentCode", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string TashvighStudentCode
		{
			get
			{
				return this._TashvighStudentCode;
			}
			set
			{
				if ((this._TashvighStudentCode != value))
				{
					if (this._Student_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTashvighStudentCodeChanging(value);
					this.SendPropertyChanging();
					this._TashvighStudentCode = value;
					this.SendPropertyChanged("TashvighStudentCode");
					this.OnTashvighStudentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Tashvigh_Tbl", Storage="_Student_Tbl", ThisKey="TashvighStudentCode", OtherKey="StudentCode", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Student_Tbl Student_Tbl
		{
			get
			{
				return this._Student_Tbl.Entity;
			}
			set
			{
				Student_Tbl previousValue = this._Student_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Student_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student_Tbl.Entity = null;
						previousValue.Tashvigh_Tbls.Remove(this);
					}
					this._Student_Tbl.Entity = value;
					if ((value != null))
					{
						value.Tashvigh_Tbls.Add(this);
						this._TashvighStudentCode = value.StudentCode;
					}
					else
					{
						this._TashvighStudentCode = default(string);
					}
					this.SendPropertyChanged("Student_Tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tazakor_Tbl")]
	public partial class Tazakor_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TazakorDate;
		
		private string _TazakorElat;
		
		private string _TazakorEghdamKonande;
		
		private string _TazakorMoredTypeTitle;
		
		private string _TazakorStudentCode;
		
		private EntityRef<Mavared_Tbl> _Mavared_Tbl;
		
		private EntityRef<Student_Tbl> _Student_Tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTazakorDateChanging(string value);
    partial void OnTazakorDateChanged();
    partial void OnTazakorElatChanging(string value);
    partial void OnTazakorElatChanged();
    partial void OnTazakorEghdamKonandeChanging(string value);
    partial void OnTazakorEghdamKonandeChanged();
    partial void OnTazakorMoredTypeTitleChanging(string value);
    partial void OnTazakorMoredTypeTitleChanged();
    partial void OnTazakorStudentCodeChanging(string value);
    partial void OnTazakorStudentCodeChanged();
    #endregion
		
		public Tazakor_Tbl()
		{
			this._Mavared_Tbl = default(EntityRef<Mavared_Tbl>);
			this._Student_Tbl = default(EntityRef<Student_Tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TazakorDate", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TazakorDate
		{
			get
			{
				return this._TazakorDate;
			}
			set
			{
				if ((this._TazakorDate != value))
				{
					this.OnTazakorDateChanging(value);
					this.SendPropertyChanging();
					this._TazakorDate = value;
					this.SendPropertyChanged("TazakorDate");
					this.OnTazakorDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TazakorElat", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TazakorElat
		{
			get
			{
				return this._TazakorElat;
			}
			set
			{
				if ((this._TazakorElat != value))
				{
					this.OnTazakorElatChanging(value);
					this.SendPropertyChanging();
					this._TazakorElat = value;
					this.SendPropertyChanged("TazakorElat");
					this.OnTazakorElatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TazakorEghdamKonande", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TazakorEghdamKonande
		{
			get
			{
				return this._TazakorEghdamKonande;
			}
			set
			{
				if ((this._TazakorEghdamKonande != value))
				{
					this.OnTazakorEghdamKonandeChanging(value);
					this.SendPropertyChanging();
					this._TazakorEghdamKonande = value;
					this.SendPropertyChanged("TazakorEghdamKonande");
					this.OnTazakorEghdamKonandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TazakorMoredTypeTitle", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string TazakorMoredTypeTitle
		{
			get
			{
				return this._TazakorMoredTypeTitle;
			}
			set
			{
				if ((this._TazakorMoredTypeTitle != value))
				{
					if (this._Mavared_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTazakorMoredTypeTitleChanging(value);
					this.SendPropertyChanging();
					this._TazakorMoredTypeTitle = value;
					this.SendPropertyChanged("TazakorMoredTypeTitle");
					this.OnTazakorMoredTypeTitleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TazakorStudentCode", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string TazakorStudentCode
		{
			get
			{
				return this._TazakorStudentCode;
			}
			set
			{
				if ((this._TazakorStudentCode != value))
				{
					if (this._Student_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTazakorStudentCodeChanging(value);
					this.SendPropertyChanging();
					this._TazakorStudentCode = value;
					this.SendPropertyChanged("TazakorStudentCode");
					this.OnTazakorStudentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mavared_Tbl_Tazakor_Tbl", Storage="_Mavared_Tbl", ThisKey="TazakorMoredTypeTitle", OtherKey="MoredTitle", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Mavared_Tbl Mavared_Tbl
		{
			get
			{
				return this._Mavared_Tbl.Entity;
			}
			set
			{
				Mavared_Tbl previousValue = this._Mavared_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Mavared_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mavared_Tbl.Entity = null;
						previousValue.Tazakor_Tbls.Remove(this);
					}
					this._Mavared_Tbl.Entity = value;
					if ((value != null))
					{
						value.Tazakor_Tbls.Add(this);
						this._TazakorMoredTypeTitle = value.MoredTitle;
					}
					else
					{
						this._TazakorMoredTypeTitle = default(string);
					}
					this.SendPropertyChanged("Mavared_Tbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Tazakor_Tbl", Storage="_Student_Tbl", ThisKey="TazakorStudentCode", OtherKey="StudentCode", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Student_Tbl Student_Tbl
		{
			get
			{
				return this._Student_Tbl.Entity;
			}
			set
			{
				Student_Tbl previousValue = this._Student_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Student_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student_Tbl.Entity = null;
						previousValue.Tazakor_Tbls.Remove(this);
					}
					this._Student_Tbl.Entity = value;
					if ((value != null))
					{
						value.Tazakor_Tbls.Add(this);
						this._TazakorStudentCode = value.StudentCode;
					}
					else
					{
						this._TazakorStudentCode = default(string);
					}
					this.SendPropertyChanged("Student_Tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Tbl")]
	public partial class User_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserName;
		
		private string _PassWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    #endregion
		
		public User_Tbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
