#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="SAP_Db")]
	public partial class SAPDbDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGheybat_Tbl(Gheybat_Tbl instance);
    partial void UpdateGheybat_Tbl(Gheybat_Tbl instance);
    partial void DeleteGheybat_Tbl(Gheybat_Tbl instance);
    partial void InsertMored_Tbl(Mored_Tbl instance);
    partial void UpdateMored_Tbl(Mored_Tbl instance);
    partial void DeleteMored_Tbl(Mored_Tbl instance);
    partial void InsertStudent_Tbl(Student_Tbl instance);
    partial void UpdateStudent_Tbl(Student_Tbl instance);
    partial void DeleteStudent_Tbl(Student_Tbl instance);
    partial void InsertTakhir_Tbl(Takhir_Tbl instance);
    partial void UpdateTakhir_Tbl(Takhir_Tbl instance);
    partial void DeleteTakhir_Tbl(Takhir_Tbl instance);
    partial void InsertTashvigh_Tbl(Tashvigh_Tbl instance);
    partial void UpdateTashvigh_Tbl(Tashvigh_Tbl instance);
    partial void DeleteTashvigh_Tbl(Tashvigh_Tbl instance);
    partial void InsertTazakor_Tbl(Tazakor_Tbl instance);
    partial void UpdateTazakor_Tbl(Tazakor_Tbl instance);
    partial void DeleteTazakor_Tbl(Tazakor_Tbl instance);
    partial void InsertUser_Tbl(User_Tbl instance);
    partial void UpdateUser_Tbl(User_Tbl instance);
    partial void DeleteUser_Tbl(User_Tbl instance);
    #endregion
		
		public SAPDbDataContext() : 
				base(global::DataAccessLayer.Properties.Settings.Default.SAP_DbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SAPDbDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAPDbDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAPDbDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SAPDbDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Gheybat_Tbl> Gheybat_Tbls
		{
			get
			{
				return this.GetTable<Gheybat_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Mored_Tbl> Mored_Tbls
		{
			get
			{
				return this.GetTable<Mored_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Student_Tbl> Student_Tbls
		{
			get
			{
				return this.GetTable<Student_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Takhir_Tbl> Takhir_Tbls
		{
			get
			{
				return this.GetTable<Takhir_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Tashvigh_Tbl> Tashvigh_Tbls
		{
			get
			{
				return this.GetTable<Tashvigh_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<Tazakor_Tbl> Tazakor_Tbls
		{
			get
			{
				return this.GetTable<Tazakor_Tbl>();
			}
		}
		
		public System.Data.Linq.Table<User_Tbl> User_Tbls
		{
			get
			{
				return this.GetTable<User_Tbl>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Gheybat_Tbl")]
	public partial class Gheybat_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _GheybatDate;
		
		private string _GheybatStudentCode;
		
		private string _GheybatStudentName;
		
		private string _GheybatType;
		
		private EntityRef<Mored_Tbl> _Mored_Tbl;
		
		private EntityRef<Student_Tbl> _Student_Tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnGheybatDateChanging(string value);
    partial void OnGheybatDateChanged();
    partial void OnGheybatStudentCodeChanging(string value);
    partial void OnGheybatStudentCodeChanged();
    partial void OnGheybatStudentNameChanging(string value);
    partial void OnGheybatStudentNameChanged();
    partial void OnGheybatTypeChanging(string value);
    partial void OnGheybatTypeChanged();
    #endregion
		
		public Gheybat_Tbl()
		{
			this._Mored_Tbl = default(EntityRef<Mored_Tbl>);
			this._Student_Tbl = default(EntityRef<Student_Tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GheybatDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string GheybatDate
		{
			get
			{
				return this._GheybatDate;
			}
			set
			{
				if ((this._GheybatDate != value))
				{
					this.OnGheybatDateChanging(value);
					this.SendPropertyChanging();
					this._GheybatDate = value;
					this.SendPropertyChanged("GheybatDate");
					this.OnGheybatDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GheybatStudentCode", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string GheybatStudentCode
		{
			get
			{
				return this._GheybatStudentCode;
			}
			set
			{
				if ((this._GheybatStudentCode != value))
				{
					if (this._Student_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGheybatStudentCodeChanging(value);
					this.SendPropertyChanging();
					this._GheybatStudentCode = value;
					this.SendPropertyChanged("GheybatStudentCode");
					this.OnGheybatStudentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GheybatStudentName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GheybatStudentName
		{
			get
			{
				return this._GheybatStudentName;
			}
			set
			{
				if ((this._GheybatStudentName != value))
				{
					this.OnGheybatStudentNameChanging(value);
					this.SendPropertyChanging();
					this._GheybatStudentName = value;
					this.SendPropertyChanged("GheybatStudentName");
					this.OnGheybatStudentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GheybatType", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string GheybatType
		{
			get
			{
				return this._GheybatType;
			}
			set
			{
				if ((this._GheybatType != value))
				{
					if (this._Mored_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnGheybatTypeChanging(value);
					this.SendPropertyChanging();
					this._GheybatType = value;
					this.SendPropertyChanged("GheybatType");
					this.OnGheybatTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mored_Tbl_Gheybat_Tbl", Storage="_Mored_Tbl", ThisKey="GheybatType", OtherKey="MoredName", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Mored_Tbl Mored_Tbl
		{
			get
			{
				return this._Mored_Tbl.Entity;
			}
			set
			{
				Mored_Tbl previousValue = this._Mored_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Mored_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mored_Tbl.Entity = null;
						previousValue.Gheybat_Tbls.Remove(this);
					}
					this._Mored_Tbl.Entity = value;
					if ((value != null))
					{
						value.Gheybat_Tbls.Add(this);
						this._GheybatType = value.MoredName;
					}
					else
					{
						this._GheybatType = default(string);
					}
					this.SendPropertyChanged("Mored_Tbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Gheybat_Tbl", Storage="_Student_Tbl", ThisKey="GheybatStudentCode", OtherKey="StudentCode", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Student_Tbl Student_Tbl
		{
			get
			{
				return this._Student_Tbl.Entity;
			}
			set
			{
				Student_Tbl previousValue = this._Student_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Student_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student_Tbl.Entity = null;
						previousValue.Gheybat_Tbls.Remove(this);
					}
					this._Student_Tbl.Entity = value;
					if ((value != null))
					{
						value.Gheybat_Tbls.Add(this);
						this._GheybatStudentCode = value.StudentCode;
					}
					else
					{
						this._GheybatStudentCode = default(string);
					}
					this.SendPropertyChanged("Student_Tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Mored_Tbl")]
	public partial class Mored_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _MoredName;
		
		private string _MoredType;
		
		private short _MoredScore;
		
		private EntitySet<Gheybat_Tbl> _Gheybat_Tbls;
		
		private EntitySet<Takhir_Tbl> _Takhir_Tbls;
		
		private EntitySet<Tashvigh_Tbl> _Tashvigh_Tbls;
		
		private EntitySet<Tazakor_Tbl> _Tazakor_Tbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnMoredNameChanging(string value);
    partial void OnMoredNameChanged();
    partial void OnMoredTypeChanging(string value);
    partial void OnMoredTypeChanged();
    partial void OnMoredScoreChanging(short value);
    partial void OnMoredScoreChanged();
    #endregion
		
		public Mored_Tbl()
		{
			this._Gheybat_Tbls = new EntitySet<Gheybat_Tbl>(new Action<Gheybat_Tbl>(this.attach_Gheybat_Tbls), new Action<Gheybat_Tbl>(this.detach_Gheybat_Tbls));
			this._Takhir_Tbls = new EntitySet<Takhir_Tbl>(new Action<Takhir_Tbl>(this.attach_Takhir_Tbls), new Action<Takhir_Tbl>(this.detach_Takhir_Tbls));
			this._Tashvigh_Tbls = new EntitySet<Tashvigh_Tbl>(new Action<Tashvigh_Tbl>(this.attach_Tashvigh_Tbls), new Action<Tashvigh_Tbl>(this.detach_Tashvigh_Tbls));
			this._Tazakor_Tbls = new EntitySet<Tazakor_Tbl>(new Action<Tazakor_Tbl>(this.attach_Tazakor_Tbls), new Action<Tazakor_Tbl>(this.detach_Tazakor_Tbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoredName", DbType="NVarChar(70) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MoredName
		{
			get
			{
				return this._MoredName;
			}
			set
			{
				if ((this._MoredName != value))
				{
					this.OnMoredNameChanging(value);
					this.SendPropertyChanging();
					this._MoredName = value;
					this.SendPropertyChanged("MoredName");
					this.OnMoredNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoredType", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string MoredType
		{
			get
			{
				return this._MoredType;
			}
			set
			{
				if ((this._MoredType != value))
				{
					this.OnMoredTypeChanging(value);
					this.SendPropertyChanging();
					this._MoredType = value;
					this.SendPropertyChanged("MoredType");
					this.OnMoredTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MoredScore", DbType="SmallInt NOT NULL")]
		public short MoredScore
		{
			get
			{
				return this._MoredScore;
			}
			set
			{
				if ((this._MoredScore != value))
				{
					this.OnMoredScoreChanging(value);
					this.SendPropertyChanging();
					this._MoredScore = value;
					this.SendPropertyChanged("MoredScore");
					this.OnMoredScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mored_Tbl_Gheybat_Tbl", Storage="_Gheybat_Tbls", ThisKey="MoredName", OtherKey="GheybatType")]
		public EntitySet<Gheybat_Tbl> Gheybat_Tbls
		{
			get
			{
				return this._Gheybat_Tbls;
			}
			set
			{
				this._Gheybat_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mored_Tbl_Takhir_Tbl", Storage="_Takhir_Tbls", ThisKey="MoredName", OtherKey="TakhirType")]
		public EntitySet<Takhir_Tbl> Takhir_Tbls
		{
			get
			{
				return this._Takhir_Tbls;
			}
			set
			{
				this._Takhir_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mored_Tbl_Tashvigh_Tbl", Storage="_Tashvigh_Tbls", ThisKey="MoredName", OtherKey="TashvighType")]
		public EntitySet<Tashvigh_Tbl> Tashvigh_Tbls
		{
			get
			{
				return this._Tashvigh_Tbls;
			}
			set
			{
				this._Tashvigh_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mored_Tbl_Tazakor_Tbl", Storage="_Tazakor_Tbls", ThisKey="MoredName", OtherKey="TazakorType")]
		public EntitySet<Tazakor_Tbl> Tazakor_Tbls
		{
			get
			{
				return this._Tazakor_Tbls;
			}
			set
			{
				this._Tazakor_Tbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Gheybat_Tbls(Gheybat_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mored_Tbl = this;
		}
		
		private void detach_Gheybat_Tbls(Gheybat_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mored_Tbl = null;
		}
		
		private void attach_Takhir_Tbls(Takhir_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mored_Tbl = this;
		}
		
		private void detach_Takhir_Tbls(Takhir_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mored_Tbl = null;
		}
		
		private void attach_Tashvigh_Tbls(Tashvigh_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mored_Tbl = this;
		}
		
		private void detach_Tashvigh_Tbls(Tashvigh_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mored_Tbl = null;
		}
		
		private void attach_Tazakor_Tbls(Tazakor_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mored_Tbl = this;
		}
		
		private void detach_Tazakor_Tbls(Tazakor_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Mored_Tbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Student_Tbl")]
	public partial class Student_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _StudentCode;
		
		private string _StudentFirstName;
		
		private string _StudentLastName;
		
		private string _StudentPayeh;
		
		private string _StudentReshteh;
		
		private string _StudentNationalCode;
		
		private System.Data.Linq.Binary _StudentProfile;
		
		private string _StudentBimary;
		
		private string _FatherFirstName;
		
		private string _FatherJob;
		
		private string _FatherMobile;
		
		private string _MotherJob;
		
		private string _MotherMobile;
		
		private bool _ParentLeft;
		
		private string _ParentDead;
		
		private string _ParentBimary;
		
		private string _HomeAddress;
		
		private string _HomeTelNumber;
		
		private short _StudentScore;
		
		private string _Other;
		
		private string _RegisterDate;
		
		private EntitySet<Gheybat_Tbl> _Gheybat_Tbls;
		
		private EntitySet<Takhir_Tbl> _Takhir_Tbls;
		
		private EntitySet<Tashvigh_Tbl> _Tashvigh_Tbls;
		
		private EntitySet<Tazakor_Tbl> _Tazakor_Tbls;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnStudentCodeChanging(string value);
    partial void OnStudentCodeChanged();
    partial void OnStudentFirstNameChanging(string value);
    partial void OnStudentFirstNameChanged();
    partial void OnStudentLastNameChanging(string value);
    partial void OnStudentLastNameChanged();
    partial void OnStudentPayehChanging(string value);
    partial void OnStudentPayehChanged();
    partial void OnStudentReshtehChanging(string value);
    partial void OnStudentReshtehChanged();
    partial void OnStudentNationalCodeChanging(string value);
    partial void OnStudentNationalCodeChanged();
    partial void OnStudentProfileChanging(System.Data.Linq.Binary value);
    partial void OnStudentProfileChanged();
    partial void OnStudentBimaryChanging(string value);
    partial void OnStudentBimaryChanged();
    partial void OnFatherFirstNameChanging(string value);
    partial void OnFatherFirstNameChanged();
    partial void OnFatherJobChanging(string value);
    partial void OnFatherJobChanged();
    partial void OnFatherMobileChanging(string value);
    partial void OnFatherMobileChanged();
    partial void OnMotherJobChanging(string value);
    partial void OnMotherJobChanged();
    partial void OnMotherMobileChanging(string value);
    partial void OnMotherMobileChanged();
    partial void OnParentLeftChanging(bool value);
    partial void OnParentLeftChanged();
    partial void OnParentDeadChanging(string value);
    partial void OnParentDeadChanged();
    partial void OnParentBimaryChanging(string value);
    partial void OnParentBimaryChanged();
    partial void OnHomeAddressChanging(string value);
    partial void OnHomeAddressChanged();
    partial void OnHomeTelNumberChanging(string value);
    partial void OnHomeTelNumberChanged();
    partial void OnStudentScoreChanging(short value);
    partial void OnStudentScoreChanged();
    partial void OnOtherChanging(string value);
    partial void OnOtherChanged();
    partial void OnRegisterDateChanging(string value);
    partial void OnRegisterDateChanged();
    #endregion
		
		public Student_Tbl()
		{
			this._Gheybat_Tbls = new EntitySet<Gheybat_Tbl>(new Action<Gheybat_Tbl>(this.attach_Gheybat_Tbls), new Action<Gheybat_Tbl>(this.detach_Gheybat_Tbls));
			this._Takhir_Tbls = new EntitySet<Takhir_Tbl>(new Action<Takhir_Tbl>(this.attach_Takhir_Tbls), new Action<Takhir_Tbl>(this.detach_Takhir_Tbls));
			this._Tashvigh_Tbls = new EntitySet<Tashvigh_Tbl>(new Action<Tashvigh_Tbl>(this.attach_Tashvigh_Tbls), new Action<Tashvigh_Tbl>(this.detach_Tashvigh_Tbls));
			this._Tazakor_Tbls = new EntitySet<Tazakor_Tbl>(new Action<Tazakor_Tbl>(this.attach_Tazakor_Tbls), new Action<Tazakor_Tbl>(this.detach_Tazakor_Tbls));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentCode", DbType="VarChar(11) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string StudentCode
		{
			get
			{
				return this._StudentCode;
			}
			set
			{
				if ((this._StudentCode != value))
				{
					this.OnStudentCodeChanging(value);
					this.SendPropertyChanging();
					this._StudentCode = value;
					this.SendPropertyChanged("StudentCode");
					this.OnStudentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentFirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string StudentFirstName
		{
			get
			{
				return this._StudentFirstName;
			}
			set
			{
				if ((this._StudentFirstName != value))
				{
					this.OnStudentFirstNameChanging(value);
					this.SendPropertyChanging();
					this._StudentFirstName = value;
					this.SendPropertyChanged("StudentFirstName");
					this.OnStudentFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentLastName", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string StudentLastName
		{
			get
			{
				return this._StudentLastName;
			}
			set
			{
				if ((this._StudentLastName != value))
				{
					this.OnStudentLastNameChanging(value);
					this.SendPropertyChanging();
					this._StudentLastName = value;
					this.SendPropertyChanged("StudentLastName");
					this.OnStudentLastNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentPayeh", DbType="NVarChar(15) NOT NULL", CanBeNull=false)]
		public string StudentPayeh
		{
			get
			{
				return this._StudentPayeh;
			}
			set
			{
				if ((this._StudentPayeh != value))
				{
					this.OnStudentPayehChanging(value);
					this.SendPropertyChanging();
					this._StudentPayeh = value;
					this.SendPropertyChanged("StudentPayeh");
					this.OnStudentPayehChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentReshteh", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string StudentReshteh
		{
			get
			{
				return this._StudentReshteh;
			}
			set
			{
				if ((this._StudentReshteh != value))
				{
					this.OnStudentReshtehChanging(value);
					this.SendPropertyChanging();
					this._StudentReshteh = value;
					this.SendPropertyChanged("StudentReshteh");
					this.OnStudentReshtehChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentNationalCode", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string StudentNationalCode
		{
			get
			{
				return this._StudentNationalCode;
			}
			set
			{
				if ((this._StudentNationalCode != value))
				{
					this.OnStudentNationalCodeChanging(value);
					this.SendPropertyChanging();
					this._StudentNationalCode = value;
					this.SendPropertyChanged("StudentNationalCode");
					this.OnStudentNationalCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentProfile", DbType="VarBinary(MAX) NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary StudentProfile
		{
			get
			{
				return this._StudentProfile;
			}
			set
			{
				if ((this._StudentProfile != value))
				{
					this.OnStudentProfileChanging(value);
					this.SendPropertyChanging();
					this._StudentProfile = value;
					this.SendPropertyChanged("StudentProfile");
					this.OnStudentProfileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentBimary", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string StudentBimary
		{
			get
			{
				return this._StudentBimary;
			}
			set
			{
				if ((this._StudentBimary != value))
				{
					this.OnStudentBimaryChanging(value);
					this.SendPropertyChanging();
					this._StudentBimary = value;
					this.SendPropertyChanged("StudentBimary");
					this.OnStudentBimaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherFirstName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string FatherFirstName
		{
			get
			{
				return this._FatherFirstName;
			}
			set
			{
				if ((this._FatherFirstName != value))
				{
					this.OnFatherFirstNameChanging(value);
					this.SendPropertyChanging();
					this._FatherFirstName = value;
					this.SendPropertyChanged("FatherFirstName");
					this.OnFatherFirstNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherJob", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string FatherJob
		{
			get
			{
				return this._FatherJob;
			}
			set
			{
				if ((this._FatherJob != value))
				{
					this.OnFatherJobChanging(value);
					this.SendPropertyChanging();
					this._FatherJob = value;
					this.SendPropertyChanged("FatherJob");
					this.OnFatherJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FatherMobile", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string FatherMobile
		{
			get
			{
				return this._FatherMobile;
			}
			set
			{
				if ((this._FatherMobile != value))
				{
					this.OnFatherMobileChanging(value);
					this.SendPropertyChanging();
					this._FatherMobile = value;
					this.SendPropertyChanged("FatherMobile");
					this.OnFatherMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherJob", DbType="NVarChar(150) NOT NULL", CanBeNull=false)]
		public string MotherJob
		{
			get
			{
				return this._MotherJob;
			}
			set
			{
				if ((this._MotherJob != value))
				{
					this.OnMotherJobChanging(value);
					this.SendPropertyChanging();
					this._MotherJob = value;
					this.SendPropertyChanged("MotherJob");
					this.OnMotherJobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MotherMobile", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string MotherMobile
		{
			get
			{
				return this._MotherMobile;
			}
			set
			{
				if ((this._MotherMobile != value))
				{
					this.OnMotherMobileChanging(value);
					this.SendPropertyChanging();
					this._MotherMobile = value;
					this.SendPropertyChanged("MotherMobile");
					this.OnMotherMobileChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentLeft", DbType="Bit NOT NULL")]
		public bool ParentLeft
		{
			get
			{
				return this._ParentLeft;
			}
			set
			{
				if ((this._ParentLeft != value))
				{
					this.OnParentLeftChanging(value);
					this.SendPropertyChanging();
					this._ParentLeft = value;
					this.SendPropertyChanged("ParentLeft");
					this.OnParentLeftChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentDead", DbType="NVarChar(7) NOT NULL", CanBeNull=false)]
		public string ParentDead
		{
			get
			{
				return this._ParentDead;
			}
			set
			{
				if ((this._ParentDead != value))
				{
					this.OnParentDeadChanging(value);
					this.SendPropertyChanging();
					this._ParentDead = value;
					this.SendPropertyChanged("ParentDead");
					this.OnParentDeadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ParentBimary", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string ParentBimary
		{
			get
			{
				return this._ParentBimary;
			}
			set
			{
				if ((this._ParentBimary != value))
				{
					this.OnParentBimaryChanging(value);
					this.SendPropertyChanging();
					this._ParentBimary = value;
					this.SendPropertyChanged("ParentBimary");
					this.OnParentBimaryChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeAddress", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string HomeAddress
		{
			get
			{
				return this._HomeAddress;
			}
			set
			{
				if ((this._HomeAddress != value))
				{
					this.OnHomeAddressChanging(value);
					this.SendPropertyChanging();
					this._HomeAddress = value;
					this.SendPropertyChanged("HomeAddress");
					this.OnHomeAddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HomeTelNumber", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string HomeTelNumber
		{
			get
			{
				return this._HomeTelNumber;
			}
			set
			{
				if ((this._HomeTelNumber != value))
				{
					this.OnHomeTelNumberChanging(value);
					this.SendPropertyChanging();
					this._HomeTelNumber = value;
					this.SendPropertyChanged("HomeTelNumber");
					this.OnHomeTelNumberChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StudentScore", DbType="SmallInt NOT NULL")]
		public short StudentScore
		{
			get
			{
				return this._StudentScore;
			}
			set
			{
				if ((this._StudentScore != value))
				{
					this.OnStudentScoreChanging(value);
					this.SendPropertyChanging();
					this._StudentScore = value;
					this.SendPropertyChanged("StudentScore");
					this.OnStudentScoreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Other", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Other
		{
			get
			{
				return this._Other;
			}
			set
			{
				if ((this._Other != value))
				{
					this.OnOtherChanging(value);
					this.SendPropertyChanging();
					this._Other = value;
					this.SendPropertyChanged("Other");
					this.OnOtherChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RegisterDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string RegisterDate
		{
			get
			{
				return this._RegisterDate;
			}
			set
			{
				if ((this._RegisterDate != value))
				{
					this.OnRegisterDateChanging(value);
					this.SendPropertyChanging();
					this._RegisterDate = value;
					this.SendPropertyChanged("RegisterDate");
					this.OnRegisterDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Gheybat_Tbl", Storage="_Gheybat_Tbls", ThisKey="StudentCode", OtherKey="GheybatStudentCode")]
		public EntitySet<Gheybat_Tbl> Gheybat_Tbls
		{
			get
			{
				return this._Gheybat_Tbls;
			}
			set
			{
				this._Gheybat_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Takhir_Tbl", Storage="_Takhir_Tbls", ThisKey="StudentCode", OtherKey="TakhirStudentCode")]
		public EntitySet<Takhir_Tbl> Takhir_Tbls
		{
			get
			{
				return this._Takhir_Tbls;
			}
			set
			{
				this._Takhir_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Tashvigh_Tbl", Storage="_Tashvigh_Tbls", ThisKey="StudentCode", OtherKey="TashvighStudentCode")]
		public EntitySet<Tashvigh_Tbl> Tashvigh_Tbls
		{
			get
			{
				return this._Tashvigh_Tbls;
			}
			set
			{
				this._Tashvigh_Tbls.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Tazakor_Tbl", Storage="_Tazakor_Tbls", ThisKey="StudentCode", OtherKey="TazakorStudentCode")]
		public EntitySet<Tazakor_Tbl> Tazakor_Tbls
		{
			get
			{
				return this._Tazakor_Tbls;
			}
			set
			{
				this._Tazakor_Tbls.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Gheybat_Tbls(Gheybat_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = this;
		}
		
		private void detach_Gheybat_Tbls(Gheybat_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = null;
		}
		
		private void attach_Takhir_Tbls(Takhir_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = this;
		}
		
		private void detach_Takhir_Tbls(Takhir_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = null;
		}
		
		private void attach_Tashvigh_Tbls(Tashvigh_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = this;
		}
		
		private void detach_Tashvigh_Tbls(Tashvigh_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = null;
		}
		
		private void attach_Tazakor_Tbls(Tazakor_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = this;
		}
		
		private void detach_Tazakor_Tbls(Tazakor_Tbl entity)
		{
			this.SendPropertyChanging();
			entity.Student_Tbl = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Takhir_Tbl")]
	public partial class Takhir_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TakhirDate;
		
		private string _TakhirStudentCode;
		
		private string _TakhirStudentName;
		
		private string _TakhirType;
		
		private EntityRef<Mored_Tbl> _Mored_Tbl;
		
		private EntityRef<Student_Tbl> _Student_Tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTakhirDateChanging(string value);
    partial void OnTakhirDateChanged();
    partial void OnTakhirStudentCodeChanging(string value);
    partial void OnTakhirStudentCodeChanged();
    partial void OnTakhirStudentNameChanging(string value);
    partial void OnTakhirStudentNameChanged();
    partial void OnTakhirTypeChanging(string value);
    partial void OnTakhirTypeChanged();
    #endregion
		
		public Takhir_Tbl()
		{
			this._Mored_Tbl = default(EntityRef<Mored_Tbl>);
			this._Student_Tbl = default(EntityRef<Student_Tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakhirDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TakhirDate
		{
			get
			{
				return this._TakhirDate;
			}
			set
			{
				if ((this._TakhirDate != value))
				{
					this.OnTakhirDateChanging(value);
					this.SendPropertyChanging();
					this._TakhirDate = value;
					this.SendPropertyChanged("TakhirDate");
					this.OnTakhirDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakhirStudentCode", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string TakhirStudentCode
		{
			get
			{
				return this._TakhirStudentCode;
			}
			set
			{
				if ((this._TakhirStudentCode != value))
				{
					if (this._Student_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTakhirStudentCodeChanging(value);
					this.SendPropertyChanging();
					this._TakhirStudentCode = value;
					this.SendPropertyChanged("TakhirStudentCode");
					this.OnTakhirStudentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakhirStudentName", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string TakhirStudentName
		{
			get
			{
				return this._TakhirStudentName;
			}
			set
			{
				if ((this._TakhirStudentName != value))
				{
					this.OnTakhirStudentNameChanging(value);
					this.SendPropertyChanging();
					this._TakhirStudentName = value;
					this.SendPropertyChanged("TakhirStudentName");
					this.OnTakhirStudentNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TakhirType", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string TakhirType
		{
			get
			{
				return this._TakhirType;
			}
			set
			{
				if ((this._TakhirType != value))
				{
					if (this._Mored_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTakhirTypeChanging(value);
					this.SendPropertyChanging();
					this._TakhirType = value;
					this.SendPropertyChanged("TakhirType");
					this.OnTakhirTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mored_Tbl_Takhir_Tbl", Storage="_Mored_Tbl", ThisKey="TakhirType", OtherKey="MoredName", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Mored_Tbl Mored_Tbl
		{
			get
			{
				return this._Mored_Tbl.Entity;
			}
			set
			{
				Mored_Tbl previousValue = this._Mored_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Mored_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mored_Tbl.Entity = null;
						previousValue.Takhir_Tbls.Remove(this);
					}
					this._Mored_Tbl.Entity = value;
					if ((value != null))
					{
						value.Takhir_Tbls.Add(this);
						this._TakhirType = value.MoredName;
					}
					else
					{
						this._TakhirType = default(string);
					}
					this.SendPropertyChanged("Mored_Tbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Takhir_Tbl", Storage="_Student_Tbl", ThisKey="TakhirStudentCode", OtherKey="StudentCode", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Student_Tbl Student_Tbl
		{
			get
			{
				return this._Student_Tbl.Entity;
			}
			set
			{
				Student_Tbl previousValue = this._Student_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Student_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student_Tbl.Entity = null;
						previousValue.Takhir_Tbls.Remove(this);
					}
					this._Student_Tbl.Entity = value;
					if ((value != null))
					{
						value.Takhir_Tbls.Add(this);
						this._TakhirStudentCode = value.StudentCode;
					}
					else
					{
						this._TakhirStudentCode = default(string);
					}
					this.SendPropertyChanged("Student_Tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tashvigh_Tbl")]
	public partial class Tashvigh_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TashvighDate;
		
		private string _TashvighElat;
		
		private string _TashvighEghdamKonande;
		
		private string _TashvighType;
		
		private string _TashvighStudentCode;
		
		private EntityRef<Mored_Tbl> _Mored_Tbl;
		
		private EntityRef<Student_Tbl> _Student_Tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTashvighDateChanging(string value);
    partial void OnTashvighDateChanged();
    partial void OnTashvighElatChanging(string value);
    partial void OnTashvighElatChanged();
    partial void OnTashvighEghdamKonandeChanging(string value);
    partial void OnTashvighEghdamKonandeChanged();
    partial void OnTashvighTypeChanging(string value);
    partial void OnTashvighTypeChanged();
    partial void OnTashvighStudentCodeChanging(string value);
    partial void OnTashvighStudentCodeChanged();
    #endregion
		
		public Tashvigh_Tbl()
		{
			this._Mored_Tbl = default(EntityRef<Mored_Tbl>);
			this._Student_Tbl = default(EntityRef<Student_Tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TashvighDate", DbType="VarChar(10)")]
		public string TashvighDate
		{
			get
			{
				return this._TashvighDate;
			}
			set
			{
				if ((this._TashvighDate != value))
				{
					this.OnTashvighDateChanging(value);
					this.SendPropertyChanging();
					this._TashvighDate = value;
					this.SendPropertyChanged("TashvighDate");
					this.OnTashvighDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TashvighElat", DbType="NVarChar(MAX)")]
		public string TashvighElat
		{
			get
			{
				return this._TashvighElat;
			}
			set
			{
				if ((this._TashvighElat != value))
				{
					this.OnTashvighElatChanging(value);
					this.SendPropertyChanging();
					this._TashvighElat = value;
					this.SendPropertyChanged("TashvighElat");
					this.OnTashvighElatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TashvighEghdamKonande", DbType="NVarChar(100)")]
		public string TashvighEghdamKonande
		{
			get
			{
				return this._TashvighEghdamKonande;
			}
			set
			{
				if ((this._TashvighEghdamKonande != value))
				{
					this.OnTashvighEghdamKonandeChanging(value);
					this.SendPropertyChanging();
					this._TashvighEghdamKonande = value;
					this.SendPropertyChanged("TashvighEghdamKonande");
					this.OnTashvighEghdamKonandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TashvighType", DbType="NVarChar(70)")]
		public string TashvighType
		{
			get
			{
				return this._TashvighType;
			}
			set
			{
				if ((this._TashvighType != value))
				{
					if (this._Mored_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTashvighTypeChanging(value);
					this.SendPropertyChanging();
					this._TashvighType = value;
					this.SendPropertyChanged("TashvighType");
					this.OnTashvighTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TashvighStudentCode", DbType="VarChar(11)")]
		public string TashvighStudentCode
		{
			get
			{
				return this._TashvighStudentCode;
			}
			set
			{
				if ((this._TashvighStudentCode != value))
				{
					if (this._Student_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTashvighStudentCodeChanging(value);
					this.SendPropertyChanging();
					this._TashvighStudentCode = value;
					this.SendPropertyChanged("TashvighStudentCode");
					this.OnTashvighStudentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mored_Tbl_Tashvigh_Tbl", Storage="_Mored_Tbl", ThisKey="TashvighType", OtherKey="MoredName", IsForeignKey=true, DeleteRule="CASCADE")]
		public Mored_Tbl Mored_Tbl
		{
			get
			{
				return this._Mored_Tbl.Entity;
			}
			set
			{
				Mored_Tbl previousValue = this._Mored_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Mored_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mored_Tbl.Entity = null;
						previousValue.Tashvigh_Tbls.Remove(this);
					}
					this._Mored_Tbl.Entity = value;
					if ((value != null))
					{
						value.Tashvigh_Tbls.Add(this);
						this._TashvighType = value.MoredName;
					}
					else
					{
						this._TashvighType = default(string);
					}
					this.SendPropertyChanged("Mored_Tbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Tashvigh_Tbl", Storage="_Student_Tbl", ThisKey="TashvighStudentCode", OtherKey="StudentCode", IsForeignKey=true, DeleteRule="CASCADE")]
		public Student_Tbl Student_Tbl
		{
			get
			{
				return this._Student_Tbl.Entity;
			}
			set
			{
				Student_Tbl previousValue = this._Student_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Student_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student_Tbl.Entity = null;
						previousValue.Tashvigh_Tbls.Remove(this);
					}
					this._Student_Tbl.Entity = value;
					if ((value != null))
					{
						value.Tashvigh_Tbls.Add(this);
						this._TashvighStudentCode = value.StudentCode;
					}
					else
					{
						this._TashvighStudentCode = default(string);
					}
					this.SendPropertyChanged("Student_Tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tazakor_Tbl")]
	public partial class Tazakor_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _TazakorDate;
		
		private string _TazakorElat;
		
		private string _TazakorEghdamKonande;
		
		private string _TazakorType;
		
		private string _TazakorStudentCode;
		
		private EntityRef<Mored_Tbl> _Mored_Tbl;
		
		private EntityRef<Student_Tbl> _Student_Tbl;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnTazakorDateChanging(string value);
    partial void OnTazakorDateChanged();
    partial void OnTazakorElatChanging(string value);
    partial void OnTazakorElatChanged();
    partial void OnTazakorEghdamKonandeChanging(string value);
    partial void OnTazakorEghdamKonandeChanged();
    partial void OnTazakorTypeChanging(string value);
    partial void OnTazakorTypeChanged();
    partial void OnTazakorStudentCodeChanging(string value);
    partial void OnTazakorStudentCodeChanged();
    #endregion
		
		public Tazakor_Tbl()
		{
			this._Mored_Tbl = default(EntityRef<Mored_Tbl>);
			this._Student_Tbl = default(EntityRef<Student_Tbl>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TazakorDate", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string TazakorDate
		{
			get
			{
				return this._TazakorDate;
			}
			set
			{
				if ((this._TazakorDate != value))
				{
					this.OnTazakorDateChanging(value);
					this.SendPropertyChanging();
					this._TazakorDate = value;
					this.SendPropertyChanged("TazakorDate");
					this.OnTazakorDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TazakorElat", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string TazakorElat
		{
			get
			{
				return this._TazakorElat;
			}
			set
			{
				if ((this._TazakorElat != value))
				{
					this.OnTazakorElatChanging(value);
					this.SendPropertyChanging();
					this._TazakorElat = value;
					this.SendPropertyChanged("TazakorElat");
					this.OnTazakorElatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TazakorEghdamKonande", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TazakorEghdamKonande
		{
			get
			{
				return this._TazakorEghdamKonande;
			}
			set
			{
				if ((this._TazakorEghdamKonande != value))
				{
					this.OnTazakorEghdamKonandeChanging(value);
					this.SendPropertyChanging();
					this._TazakorEghdamKonande = value;
					this.SendPropertyChanged("TazakorEghdamKonande");
					this.OnTazakorEghdamKonandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TazakorType", DbType="NVarChar(70) NOT NULL", CanBeNull=false)]
		public string TazakorType
		{
			get
			{
				return this._TazakorType;
			}
			set
			{
				if ((this._TazakorType != value))
				{
					if (this._Mored_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTazakorTypeChanging(value);
					this.SendPropertyChanging();
					this._TazakorType = value;
					this.SendPropertyChanged("TazakorType");
					this.OnTazakorTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TazakorStudentCode", DbType="VarChar(11) NOT NULL", CanBeNull=false)]
		public string TazakorStudentCode
		{
			get
			{
				return this._TazakorStudentCode;
			}
			set
			{
				if ((this._TazakorStudentCode != value))
				{
					if (this._Student_Tbl.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTazakorStudentCodeChanging(value);
					this.SendPropertyChanging();
					this._TazakorStudentCode = value;
					this.SendPropertyChanged("TazakorStudentCode");
					this.OnTazakorStudentCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Mored_Tbl_Tazakor_Tbl", Storage="_Mored_Tbl", ThisKey="TazakorType", OtherKey="MoredName", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Mored_Tbl Mored_Tbl
		{
			get
			{
				return this._Mored_Tbl.Entity;
			}
			set
			{
				Mored_Tbl previousValue = this._Mored_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Mored_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Mored_Tbl.Entity = null;
						previousValue.Tazakor_Tbls.Remove(this);
					}
					this._Mored_Tbl.Entity = value;
					if ((value != null))
					{
						value.Tazakor_Tbls.Add(this);
						this._TazakorType = value.MoredName;
					}
					else
					{
						this._TazakorType = default(string);
					}
					this.SendPropertyChanged("Mored_Tbl");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Student_Tbl_Tazakor_Tbl", Storage="_Student_Tbl", ThisKey="TazakorStudentCode", OtherKey="StudentCode", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Student_Tbl Student_Tbl
		{
			get
			{
				return this._Student_Tbl.Entity;
			}
			set
			{
				Student_Tbl previousValue = this._Student_Tbl.Entity;
				if (((previousValue != value) 
							|| (this._Student_Tbl.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Student_Tbl.Entity = null;
						previousValue.Tazakor_Tbls.Remove(this);
					}
					this._Student_Tbl.Entity = value;
					if ((value != null))
					{
						value.Tazakor_Tbls.Add(this);
						this._TazakorStudentCode = value.StudentCode;
					}
					else
					{
						this._TazakorStudentCode = default(string);
					}
					this.SendPropertyChanged("Student_Tbl");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.User_Tbl")]
	public partial class User_Tbl : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _UserName;
		
		private string _PassWord;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnUserNameChanging(string value);
    partial void OnUserNameChanged();
    partial void OnPassWordChanging(string value);
    partial void OnPassWordChanged();
    #endregion
		
		public User_Tbl()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserName
		{
			get
			{
				return this._UserName;
			}
			set
			{
				if ((this._UserName != value))
				{
					this.OnUserNameChanging(value);
					this.SendPropertyChanging();
					this._UserName = value;
					this.SendPropertyChanged("UserName");
					this.OnUserNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PassWord", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string PassWord
		{
			get
			{
				return this._PassWord;
			}
			set
			{
				if ((this._PassWord != value))
				{
					this.OnPassWordChanging(value);
					this.SendPropertyChanging();
					this._PassWord = value;
					this.SendPropertyChanged("PassWord");
					this.OnPassWordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
